baseURL = "https://dmitryvk.github.io/"
languageCode = "en-us"
title = "dmitry_vk's notes"
theme = "slick"
publishDir = "docs"

[taxonomies]
tags = "tags"
series = "series"

paginate = 10
paginatePath = "page"

[params]
showNavHeader = true
showMetaDates = true
dateFmt = "02 Jan 2006"


[author]
name = "Dmitry Kalanov"
email = "Kalyanov.Dmitry@gmail.com"

[services.rss]
# limit the length of the rss feed (default: unlimited)
limit = 0

[menu]

[[menu.main]]
identifier = "posts"
name = "Posts"
title = "All posts"
url = "/"
weight = 1


[[menu.footer]]
name = "Github"
title = "Github"
url = "https://github.com/dmitryvk"
weight = 1
